/**
 * ============================================
 * Data Quality — Seed: Классификационные правила
 * ============================================
 * Проверяют соответствие описания операции счёту.
 */

import { DataQualityRule } from './types';

export const SEED_CLASSIFICATION: Partial<DataQualityRule>[] = [
  // ============================================
  // MUST_CONTAIN — что должно быть в описании
  // ============================================
  {
    name: 'Зарплата должна содержать "зарплат/оклад/выплат"',
    description: 'Счёт «Зарплата» — только для выплат сотрудникам',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-salary' },
    params: { keywords: ['зарплат', 'оклад', 'выплат', 'зп '] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Премии должны содержать "преми/бонус"',
    description: 'Счёт «Премии» — только для премий и бонусов',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-bonus' },
    params: { keywords: ['преми', 'бонус'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Аренда должна содержать "аренд"',
    description: 'Общий счёт аренды',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-rent' },
    params: { keywords: ['аренд'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Аренда офиса должна содержать "аренд/офис"',
    description: 'Счёт «Аренда офиса» — только для аренды офиса',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-rent-office' },
    params: { keywords: ['аренд', 'офис'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Аренда склада должна содержать "аренд/склад"',
    description: 'Счёт «Аренда склада» — только для аренды склада',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-rent-warehouse' },
    params: { keywords: ['аренд', 'склад'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Коммунальные должны содержать "коммунал/электро/вода/газ"',
    description: 'Счёт «Коммунальные» — только для коммунальных платежей',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-utilities' },
    params: { keywords: ['коммунал', 'электро', 'вода', 'газ', 'отоплени'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Связь и интернет должны содержать "связь/интернет/телефон"',
    description: 'Счёт «Связь и интернет»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-internet' },
    params: { keywords: ['связь', 'интернет', 'телефон', 'мобильн'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'ПО должно содержать "программ/по/лиценз/софт"',
    description: 'Счёт «Программное обеспечение»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-software' },
    params: { keywords: ['программ', ' лиценз', 'софт', 'подписк'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Обслуживание техники должно содержать "техник/обслужива/ремонт"',
    description: 'Счёт «Обслуживание техники»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-tech' },
    params: { keywords: ['техник', 'обслужива', 'ремонт'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Маркетинг должен содержать "реклам/маркетинг/промо"',
    description: 'Счёт «Реклама» — для маркетинговых операций',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-marketing' },
    params: { keywords: ['реклам', 'маркетинг', 'промо'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'PR и мероприятия должны содержать "pr/мероприяти/спонсор"',
    description: 'Счёт «PR и мероприятия»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-pr' },
    params: { keywords: ['pr', 'мероприяти', 'спонсор', 'событи'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Обучение должно содержать "обучен/курс/тренинг/семинар"',
    description: 'Счёт «Обучение»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-training' },
    params: { keywords: ['обучен', 'курс', 'тренинг', 'семинар'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Банковские комиссии должны содержать "комисси"',
    description: 'Счёт «Банковские комиссии»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-bank-fees' },
    params: { keywords: ['комисси'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Закупка товаров должна содержать "закупк/товар"',
    description: 'Счёт «Закупка товаров»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-goods' },
    params: { keywords: ['закупк', 'товар'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Материалы должны содержать "материал"',
    description: 'Счёт «Материалы»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-materials' },
    params: { keywords: ['материал'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Упаковка должна содержать "упаковк"',
    description: 'Счёт «Упаковка»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-packaging' },
    params: { keywords: ['упаковк', 'тара'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Производственные расходы должны содержать "производств"',
    description: 'Счёт «Производственные расходы»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-production' },
    params: { keywords: ['производств'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Субподряд должен содержать "субподряд/подряд"',
    description: 'Счёт «Субподряд»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-subcontract' },
    params: { keywords: ['субподряд', 'подряд'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Логистика должна содержать "логист/доставк/транспорт"',
    description: 'Счёт «Логистика»',
    category: 'classification',
    rule_type: 'must_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-logistics' },
    params: { keywords: ['логист', 'доставк', 'транспорт', 'перевозк'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },

  // ============================================
  // MUST_NOT_CONTAIN — чего не должно быть
  // ============================================
  {
    name: 'Обучение не содержит слов других категорий',
    description: 'Оплаты на счёте «Обучение» не должны содержать слов из других категорий',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-training' },
    params: { keywords: ['аренд', 'зарплат', 'реклам', 'комисси', 'закупк', 'доставк'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Логистика не содержит слов других категорий',
    description: 'На счёте «Логистика» не должно быть рекламы, аренды, обучения',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-cogs-logistics' },
    params: { keywords: ['реклам', 'аренд', 'обучен', 'зарплат'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Аренда офиса не содержит "склад/обучен"',
    description: 'Счёт «Аренда офиса» — не для склада и не для обучения',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-rent-office' },
    params: { keywords: ['склад', 'обучен', 'зарплат', 'реклам'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Аренда склада не содержит "офис/обучен"',
    description: 'Счёт «Аренда склада» — не для офиса и не для обучения',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-rent-warehouse' },
    params: { keywords: ['офис', 'обучен', 'зарплат', 'реклам'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Маркетинг не содержит слов других категорий',
    description: 'На счёте «Реклама» не должно быть аренды, зарплат, комиссий',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-marketing' },
    params: { keywords: ['аренд', 'зарплат', 'комисси', 'закупк'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Зарплата не содержит слов других категорий',
    description: 'На счёте «Зарплата» не должно быть аренды, рекламы, комиссий',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-salary' },
    params: { keywords: ['аренд', 'реклам', 'комисси', 'закупк', 'обучен'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
  {
    name: 'Банковские комиссии не содержат слов других категорий',
    description: 'На счёте «Банковские комиссии» не должно быть аренды, зарплат, рекламы',
    category: 'classification',
    rule_type: 'must_not_contain',
    entity_type: 'Transactions',
    target_field: 'description',
    condition: { debit_account_id: 'acc-out-bank-fees' },
    params: { keywords: ['аренд', 'зарплат', 'реклам', 'закупк', 'обучен'] },
    severity: 'warning',
    is_active: true,
    auto_apply: false,
  },
];
